import swaggerJsdoc from 'swagger-jsdoc';
import { config } from '@config/index';

export const openapiSpec = swaggerJsdoc({
  definition: {
    openapi: '3.0.3',
    info: {
      title: 'Beats API',
      version: '1.0.0',
      description: 'REST API for the beats marketplace.',
    },
    servers: [{ url: `${config.app.url}/api/v1`, description: config.env }],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
        },
      },
      parameters: {
        page: {
          in: 'query',
          name: 'page',
          schema: { type: 'integer', minimum: 1, default: 1 },
          description: 'Page number',
        },
        limit: {
          in: 'query',
          name: 'limit',
          schema: { type: 'integer', minimum: 1, maximum: 100, default: 20 },
          description: 'Items per page',
        },
      },
      schemas: {
        SuccessEnvelope: {
          type: 'object',
          required: ['success', 'code', 'message', 'data'],
          properties: {
            success: { type: 'boolean', example: true },
            code: { type: 'integer', example: 200 },
            message: { type: 'string', example: 'OK' },
            data: {},
            meta: { type: 'object', additionalProperties: true },
          },
        },
        ErrorEnvelope: {
          type: 'object',
          required: ['success', 'code', 'message'],
          properties: {
            success: { type: 'boolean', example: false },
            code: { type: 'integer', example: 422 },
            message: { type: 'string', example: 'VALIDATION_ERROR' },
            details: { type: 'object', additionalProperties: true },
            errors: {
              type: 'object',
              description: 'Field-level validation errors keyed by field name. Present only on 422 responses.',
              additionalProperties: { type: 'string' },
              example: { email: 'Invalid email', firstName: 'Required' },
            },
          },
        },
        PaginationMeta: {
          type: 'object',
          required: ['page', 'limit', 'total', 'hasNextPage', 'hasPrevPage'],
          properties: {
            page: { type: 'integer', example: 1 },
            limit: { type: 'integer', example: 20 },
            total: { type: 'integer', example: 100 },
            hasNextPage: { type: 'boolean', example: true },
            hasPrevPage: { type: 'boolean', example: false },
          },
        },
        TokenPair: {
          type: 'object',
          properties: {
            accessToken: { type: 'string', example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...' },
            refreshToken: { type: 'string', example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...' },
          },
        },
        UserProfile: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid', example: '01935aaa-bbbb-7ccc-dddd-eeeeffff0000' },
            firstName: { type: 'string', example: 'John' },
            lastName: { type: 'string', example: 'Doe' },
            userName: { type: 'string', nullable: true, example: 'johndoe' },
            email: { type: 'string', format: 'email', example: 'john.doe@example.com' },
            avatar: { type: 'string', format: 'uri', nullable: true, example: 'https://eu2.contabostorage.com/...' },
            role: { type: 'string', enum: ['user', 'producer', 'admin'], example: 'user' },
            profileHeading: { type: 'string', nullable: true, example: 'Producer & Beatmaker' },
            profileDescription: { type: 'string', nullable: true },
            profileContactEmail: { type: 'string', format: 'email', nullable: true },
            profileSocialLinks: {
              type: 'object',
              nullable: true,
              properties: {
                twitter: { type: 'string', format: 'uri' },
                instagram: { type: 'string', format: 'uri' },
                facebook: { type: 'string', format: 'uri' },
                youtube: { type: 'string', format: 'uri' },
                soundcloud: { type: 'string', format: 'uri' },
                spotify: { type: 'string', format: 'uri' },
                website: { type: 'string', format: 'uri' },
              },
            },
            createdAt: { type: 'string', format: 'date-time' },
          },
        },
        Beat: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid', example: '01935678-1234-7890-abcd-1234567890ab' },
            name: { type: 'string', example: 'Dark Trap' },
            slug: { type: 'string', example: 'dark-trap' },
            description: { type: 'string', example: 'Hard-hitting 808s' },
            thumbnail: { type: 'string', format: 'uri', nullable: true },
            previewType: { type: 'string', example: 'audio' },
            previewImage: { type: 'string', format: 'uri', nullable: true },
            previewVideo: { type: 'string', format: 'uri', nullable: true },
            previewAudio: { type: 'string', format: 'uri', nullable: true },
            regularPrice: { type: 'number', example: 29.99 },
            extendedPrice: { type: 'number', example: 99.99 },
            bpm: { type: 'integer', nullable: true, example: 140 },
            musicKey: { type: 'string', nullable: true, example: 'Am' },
            tags: { type: 'array', items: { type: 'string' }, example: ['trap', 'dark'] },
            isFree: { type: 'boolean', example: false },
            isFeatured: { type: 'boolean', example: false },
            isTrending: { type: 'boolean', example: false },
            isBestSelling: { type: 'boolean', example: false },
            isPremium: { type: 'boolean', example: false },
            isOnDiscount: { type: 'boolean', example: false },
            purchasingStatus: { type: 'boolean', example: true },
            totalSales: { type: 'integer', example: 0 },
            totalReviews: { type: 'integer', example: 0 },
            avgReviews: { type: 'number', example: 0 },
            totalViews: { type: 'integer', example: 0 },
            author: {
              type: 'object',
              properties: {
                id: { type: 'string', format: 'uuid', example: '0193abcd-5678-7def-9012-3456789abcde' },
                firstName: { type: 'string', nullable: true, example: 'John' },
                lastName: { type: 'string', nullable: true, example: 'Doe' },
                userName: { type: 'string', nullable: true, example: 'johndoe' },
                avatar: { type: 'string', format: 'uri', nullable: true },
              },
            },
            category: {
              type: 'object',
              properties: {
                id: { type: 'string', format: 'uuid', example: '01935678-1234-7890-abcd-1234567890ab' },
                name: { type: 'string', example: 'Hip-Hop' },
                slug: { type: 'string', example: 'hip-hop' },
              },
            },
            subCategory: {
              type: 'object',
              nullable: true,
              properties: {
                id: { type: 'string', format: 'uuid', example: '01934567-89ab-7cde-f012-3456789abcde' },
                name: { type: 'string', example: 'Trap' },
                slug: { type: 'string', example: 'trap' },
              },
            },
            createdAt: { type: 'string', format: 'date-time', nullable: true },
            updatedAt: { type: 'string', format: 'date-time', nullable: true },
          },
        },
        BeatWrite: {
          type: 'object',
          required: ['title', 'regularPrice', 'extendedPrice', 'categoryId'],
          properties: {
            beatFile: { type: 'string', format: 'binary', description: 'Audio file (MP3, WAV, FLAC, AAC) — max 100 MB. Required on create.' },
            coverImage: { type: 'string', format: 'binary', description: 'Cover image (JPEG, PNG, WebP, GIF) — max 5 MB.' },
            title: { type: 'string', minLength: 1, maxLength: 100, example: 'Dark Trap' },
            description: { type: 'string', maxLength: 5000 },
            bpm: { type: 'integer', minimum: 1, maximum: 400, example: 140 },
            musicKey: { type: 'string', maxLength: 10, example: 'Am' },
            regularPrice: { type: 'string', example: '29.99' },
            extendedPrice: { type: 'string', example: '99.99' },
            isFree: { type: 'string', enum: ['true', 'false'], default: 'false' },
            tags: { type: 'string', example: 'trap,dark,808', description: 'Comma-separated or JSON array string' },
            categoryId: { type: 'string', format: 'uuid', example: '01935aaa-bbbb-7ccc-dddd-eeeeffff0000' },
            subCategoryId: { type: 'string', format: 'uuid' },
          },
        },
        EarningRecord: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid', example: '01935678-1234-7890-abcd-1234567890ab' },
            itemId: { type: 'string', format: 'uuid', example: '0193abcd-5678-7def-9012-3456789abcde', description: 'Beat (item) ID' },
            buyerId: { type: 'string', format: 'uuid', example: '01935aaa-bbbb-7ccc-dddd-eeeeffff0000', description: 'User who purchased' },
            licenseType: { type: 'string', enum: ['regular', 'extended'], example: 'regular' },
            salePrice: { type: 'string', example: '29.99', description: 'Total sale amount' },
            authorEarning: { type: 'string', example: '20.99', description: 'Producer earnings after fees' },
            soldAt: { type: 'string', format: 'date-time', nullable: true },
          },
        },
        CartItem: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid', example: '01935678-1234-7890-abcd-1234567890ab' },
            itemId: { type: 'string', format: 'uuid', example: '0193abcd-5678-7def-9012-3456789abcde' },
            licenseType: { type: 'string', enum: ['regular', 'extended'], example: 'regular' },
            quantity: { type: 'integer', example: 1 },
            item: {
              type: 'object',
              properties: {
                id: { type: 'string', format: 'uuid', example: '0193abcd-5678-7def-9012-3456789abcde' },
                name: { type: 'string', example: 'Dark Trap' },
                slug: { type: 'string', example: 'dark-trap' },
                thumbnail: { type: 'string', nullable: true },
                regularPrice: { type: 'number', example: 29.99 },
                extendedPrice: { type: 'number', example: 99.99 },
                bpm: { type: 'integer', nullable: true, example: 140 },
              },
            },
          },
        },
        OrderItem: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid', example: '01935678-1234-7890-abcd-1234567890ab' },
            itemId: { type: 'string', format: 'uuid', nullable: true, example: '0193abcd-5678-7def-9012-3456789abcde' },
            name: { type: 'string', nullable: true, example: 'Dark Trap' },
            slug: { type: 'string', nullable: true, example: 'dark-trap' },
            thumbnail: { type: 'string', nullable: true },
            licenseType: { type: 'string', enum: ['regular', 'extended'] },
            price: { type: 'number', example: 29.99 },
            quantity: { type: 'integer', example: 1 },
            total: { type: 'number', example: 29.99 },
          },
        },
        Order: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid', example: '01935678-1234-7890-abcd-1234567890ab' },
            amount: { type: 'number', description: 'Subtotal charged, in NGN (settlement currency)', example: 160000 },
            fees: { type: 'number', description: 'Gateway fee, in NGN', example: 4800 },
            total: { type: 'number', description: 'Grand total charged, in NGN', example: 164800 },
            currency: { type: 'string', example: 'NGN', description: 'Settlement currency — always NGN' },
            displayCurrency: { type: 'string', enum: ['USD', 'EUR', 'GBP', 'JPY', 'CNY', 'NGN'], example: 'USD', description: 'Currency the buyer checked out in' },
            displayTotal: { type: 'number', description: 'Grand total in the buyer\'s display currency', example: 103 },
            status: { type: 'string', enum: ['pending', 'paid', 'failed', 'cancelled'], example: 'paid' },
            createdAt: { type: 'string', format: 'date-time' },
            items: { type: 'array', items: { $ref: '#/components/schemas/OrderItem' } },
          },
        },
        Category: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid', example: '01935aaa-bbbb-7ccc-dddd-eeeeffff0000' },
            name: { type: 'string', example: 'Hip-Hop' },
            slug: { type: 'string', example: 'hip-hop' },
          },
        },
        CategoryDetail: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid', example: '01935aaa-bbbb-7ccc-dddd-eeeeffff0000' },
            name: { type: 'string', example: 'Hip Hop' },
            slug: { type: 'string', example: 'hip-hop' },
            title: { type: 'string', nullable: true, example: 'Buy Hip Hop Beats & Tracks' },
            description: { type: 'string', nullable: true },
            regularBuyerFee: { type: 'number', example: 29 },
            extendedBuyerFee: { type: 'number', example: 100 },
            fileType: { type: 'boolean', nullable: true, example: true },
            thumbnailWidth: { type: 'integer', example: 512 },
            thumbnailHeight: { type: 'integer', example: 512 },
            previewImageWidth: { type: 'integer', nullable: true, example: 1080 },
            previewImageHeight: { type: 'integer', nullable: true, example: 1080 },
            maximumScreenshots: { type: 'integer', nullable: true, example: 5 },
            mainFileTypes: { type: 'string', example: 'zip,rar,mp3,wav,mp4' },
            maxPreviewFileSize: { type: 'integer', example: 524288000 },
            views: { type: 'integer', example: 266 },
            sortId: { type: 'integer', example: 2 },
            createdAt: { type: 'string', format: 'date-time', nullable: true },
            updatedAt: { type: 'string', format: 'date-time', nullable: true },
          },
        },
        CategoryWrite: {
          type: 'object',
          required: ['name'],
          description: 'Category create/update body. On update, send only the fields to change (at least one).',
          properties: {
            name: { type: 'string', minLength: 1, maxLength: 255, example: 'Hip Hop' },
            slug: {
              type: 'string',
              maxLength: 255,
              pattern: '^[a-z0-9]+(?:-[a-z0-9]+)*$',
              description: 'Optional. Auto-generated from name when omitted.',
              example: 'hip-hop',
            },
            title: { type: 'string', maxLength: 255 },
            description: { type: 'string', maxLength: 255 },
            regularBuyerFee: { type: 'number', minimum: 0, example: 29 },
            extendedBuyerFee: { type: 'number', minimum: 0, example: 100 },
            fileType: { type: 'boolean' },
            thumbnailWidth: { type: 'integer', minimum: 0, example: 512 },
            thumbnailHeight: { type: 'integer', minimum: 0, example: 512 },
            previewImageWidth: { type: 'integer', minimum: 0, example: 1080 },
            previewImageHeight: { type: 'integer', minimum: 0, example: 1080 },
            maximumScreenshots: { type: 'integer', minimum: 0, example: 5 },
            mainFileTypes: { type: 'string', maxLength: 255, example: 'zip,rar,mp3,wav,mp4' },
            maxPreviewFileSize: { type: 'integer', minimum: 0, example: 524288000 },
            sortId: { type: 'integer', minimum: 0, example: 2 },
          },
        },
        CheckoutGatewayOption: {
          type: 'object',
          description: 'Fee and total are in the buyer\'s display currency. chargeTotal is the actual NGN amount the gateway will charge.',
          properties: {
            alias: { type: 'string', enum: ['paystack', 'flutterwave', 'opay'], example: 'paystack' },
            name: { type: 'string', example: 'Paystack' },
            logo: { type: 'string', example: 'payment-gateways/paystack.svg' },
            feePercent: { type: 'number', example: 3 },
            fee: { type: 'number', description: 'Gateway fee in the display currency', example: 3 },
            total: { type: 'number', description: 'Grand total in the display currency', example: 103 },
            chargeCurrency: { type: 'string', enum: ['NGN'], example: 'NGN', description: 'Settlement currency — always NGN' },
            chargeTotal: { type: 'number', description: 'Actual amount charged at the gateway, in NGN', example: 164800 },
          },
        },
        CheckoutPage: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid', example: '01935678-1234-7890-abcd-1234567890ab' },
            currency: { type: 'string', enum: ['USD', 'EUR', 'GBP', 'JPY', 'CNY', 'NGN'], example: 'USD', description: 'Display currency the buyer selected' },
            settlementCurrency: { type: 'string', enum: ['NGN'], example: 'NGN', description: 'Currency the payment is actually charged/settled in' },
            subtotal: { type: 'number', description: 'Subtotal in the display currency', example: 100 },
            items: { type: 'array', items: { $ref: '#/components/schemas/OrderItem' } },
            gateways: { type: 'array', items: { $ref: '#/components/schemas/CheckoutGatewayOption' } },
          },
        },
        BillingAddress: {
          type: 'object',
          required: ['firstName', 'lastName', 'address1', 'city', 'state', 'postalCode', 'country'],
          properties: {
            firstName: { type: 'string', example: 'John' },
            lastName: { type: 'string', example: 'Doe' },
            address1: { type: 'string', example: '123 Allen Ave' },
            address2: { type: 'string', example: 'Suite 5' },
            city: { type: 'string', example: 'Ikeja' },
            state: { type: 'string', example: 'Lagos' },
            postalCode: { type: 'string', example: '100001' },
            country: { type: 'string', example: 'NG', description: 'ISO 3166-1 alpha-2 code' },
          },
        },
        PayRequest: {
          type: 'object',
          required: ['gateway', 'currency', 'billing'],
          properties: {
            gateway: { type: 'string', enum: ['paystack', 'flutterwave', 'opay'], example: 'paystack' },
            currency: {
              type: 'string',
              enum: ['USD', 'EUR', 'GBP', 'JPY', 'CNY', 'NGN'],
              example: 'USD',
              description: 'Must match the display currency chosen at checkout. The charge always settles in NGN.',
            },
            billing: { $ref: '#/components/schemas/BillingAddress' },
          },
        },
        DownloadGrant: {
          type: 'object',
          properties: {
            purchaseId: { type: 'string', format: 'uuid', example: '01935678-1234-7890-abcd-1234567890ab', description: 'purchases.id' },
            beatId: { type: 'string', format: 'uuid', example: '0193abcd-5678-7def-9012-3456789abcde' },
            beatName: { type: 'string', example: 'Dark Trap' },
            licenseType: { type: 'string', enum: ['regular', 'extended'], example: 'regular' },
            url: { type: 'string', format: 'uri', example: 'https://eu2.contabostorage.com/...?X-Amz-Signature=...', description: 'Pre-signed S3 URL, valid for 1 hour' },
            expiresAt: { type: 'string', format: 'date-time', example: '2025-05-08T13:00:00.000Z' },
          },
        },
        PlaylistItem: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid', example: '01935678-1234-7890-abcd-1234567890ab', description: 'playlist_item record ID' },
            beatId: { type: 'string', format: 'uuid', example: '0193abcd-5678-7def-9012-3456789abcde' },
            beatName: { type: 'string', example: 'Dark Trap' },
            beatSlug: { type: 'string', example: 'dark-trap' },
            thumbnail: { type: 'string', nullable: true, example: 'https://eu2.contabostorage.com/...' },
            position: { type: 'integer', example: 0 },
            addedAt: { type: 'string', format: 'date-time', nullable: true },
          },
        },
        Playlist: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid', example: '01935678-1234-7890-abcd-1234567890ab' },
            name: { type: 'string', example: 'My Trap Beats' },
            description: { type: 'string', nullable: true },
            isPublic: { type: 'boolean', example: false },
            itemCount: { type: 'integer', example: 3 },
            items: { type: 'array', items: { $ref: '#/components/schemas/PlaylistItem' } },
            createdAt: { type: 'string', format: 'date-time', nullable: true },
          },
        },
        Purchase: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid', example: '01935678-1234-7890-abcd-1234567890ab', description: 'Purchase ID — use this with GET /downloads/{id}' },
            code: { type: 'string', example: 'BP-A3F7BC2D1E4F', description: 'License code' },
            itemId: { type: 'string', format: 'uuid', example: '0193abcd-5678-7def-9012-3456789abcde' },
            name: { type: 'string', nullable: true, example: 'Dark Trap' },
            slug: { type: 'string', nullable: true, example: 'dark-trap' },
            thumbnail: { type: 'string', nullable: true, example: 'https://eu2.contabostorage.com/beats/dark-trap.jpg' },
            licenseType: { type: 'string', enum: ['regular', 'extended'], example: 'regular' },
            isDownloaded: { type: 'boolean', example: false },
            purchasedAt: { type: 'string', format: 'date-time', nullable: true },
          },
        },
        Favorite: {
          allOf: [
            { $ref: '#/components/schemas/Beat' },
            {
              type: 'object',
              properties: {
                favoritedAt: {
                  type: 'string',
                  format: 'date-time',
                  nullable: true,
                  description: 'When the user added this beat to their favorites',
                },
              },
            },
          ],
        },
      },
      responses: {
        BadRequest: {
          description: 'Bad request',
          content: {
            'application/json': { schema: { $ref: '#/components/schemas/ErrorEnvelope' } },
          },
        },
        Unauthorized: {
          description: 'Missing or invalid access token',
          content: {
            'application/json': { schema: { $ref: '#/components/schemas/ErrorEnvelope' } },
          },
        },
        Forbidden: {
          description: 'Insufficient role/permissions',
          content: {
            'application/json': { schema: { $ref: '#/components/schemas/ErrorEnvelope' } },
          },
        },
        NotFound: {
          description: 'Resource not found',
          content: {
            'application/json': { schema: { $ref: '#/components/schemas/ErrorEnvelope' } },
          },
        },
        ValidationError: {
          description: 'Request validation failed — errors object contains one message per field',
          content: {
            'application/json': {
              schema: {
                allOf: [
                  { $ref: '#/components/schemas/ErrorEnvelope' },
                  {
                    type: 'object',
                    properties: {
                      errors: {
                        type: 'object',
                        additionalProperties: { type: 'string' },
                        example: { email: 'Invalid email', firstName: 'Required' },
                      },
                    },
                  },
                ],
              },
            },
          },
        },
      },
    },
    security: [{ bearerAuth: [] }],
    tags: [
      { name: 'Auth', description: 'Registration, login, and token management' },
      { name: 'Users', description: 'User profile and avatar' },
      { name: 'Beats', description: 'Beat catalogue and producer writes' },
      { name: 'Categories', description: 'Genre categories' },
      { name: 'Cart', description: 'Shopping cart management' },
      { name: 'Orders', description: 'Purchase history, validation, and checkout' },
      { name: 'Payments', description: 'Checkout sessions, gateway payment init, callbacks, and webhooks' },
      { name: 'Dashboard', description: 'Producer earnings and sales analytics (PRODUCER/ADMIN only)' },
      { name: 'Downloads', description: 'Signed download URLs for purchased beats' },
      { name: 'Playlists', description: 'User playlist management' },
      { name: 'Favorites', description: 'Save beats to a personal favorites list' },
      { name: 'Purchases', description: "Buyer's completed purchases and license codes" },
    ],
    paths: {},
  },
  apis: [
    './src/modules/**/routes.ts',
    './dist/modules/**/routes.js',
  ],
});
