-- ============================================================
-- UUID PK MIGRATION — auto-generated, data-preserving
-- ============================================================
-- Strategy:
--   Phase A: For every table, add `id_new CHAR(36)` and backfill via UUID()
--   Phase B: For every FK column, add `<col>_new CHAR(36)` and backfill via JOIN
--   Phase C: Drop FK constraints
--   Phase D: Drop old PK/FK columns, rename _new → original
--   Phase E: Re-add PRIMARY KEY and FK constraints
-- ============================================================
-- UUID() is non-deterministic, so STATEMENT-based binlog rejects it (error 1674).
-- Switch this session to ROW-based binlog so per-row UUID values are logged literally,
-- and disable bin-logging entirely as a defensive fallback for setups that lock the format.
SET SESSION sql_log_bin = 0;
SET SESSION binlog_format = 'ROW';

SET FOREIGN_KEY_CHECKS = 0;

-- ── Phase A: Add UUID id_new for every table ───────────────
ALTER TABLE `addons` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `admin_notifications` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `admins` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `ads` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `author_taxes` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `badges` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `blog_articles` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `blog_categories` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `blog_comments` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `bottom_nav_links` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `buyer_taxes` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `captcha_providers` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `cart_items` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `categories` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `category_options` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `category_reviewer` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `currencies` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `editor_images` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `extensions` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `failed_jobs` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `faqs` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `favorites` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `followers` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `footer_links` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `help_articles` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `help_categories` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `home_categories` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `home_sections` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `item_change_logs` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `item_comment_replies` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `item_comment_reports` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `item_comments` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `item_discounts` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `item_histories` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `item_review_replies` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `item_reviews` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `item_updates` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `item_views` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `items` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `jobs` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `kyc_verifications` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `levels` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `mail_templates` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `oauth_providers` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `pages` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `payment_gateways` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `plans` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `playlist_items` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `playlists` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `premium_earnings` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `purchases` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `referral_earnings` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `referrals` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `refresh_tokens` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `refund_replies` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `refunds` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `reviewers` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `sales` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `settings` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `statements` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `storage_providers` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `sub_categories` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `subscriptions` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `support_earnings` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `support_periods` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `testimonials` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `themes` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `ticket_categories` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `ticket_replies` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `ticket_reply_attachments` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `tickets` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `top_nav_links` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `transaction_items` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `transactions` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `translates` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `uploaded_files` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `user_badges` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `user_login_logs` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `users` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `withdrawal_methods` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());
ALTER TABLE `withdrawals` ADD COLUMN `id_new` CHAR(36) NOT NULL DEFAULT (UUID());

-- Force-backfill any rows where the DEFAULT did not apply
UPDATE `addons` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `admin_notifications` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `admins` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `ads` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `author_taxes` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `badges` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `blog_articles` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `blog_categories` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `blog_comments` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `bottom_nav_links` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `buyer_taxes` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `captcha_providers` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `cart_items` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `categories` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `category_options` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `category_reviewer` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `currencies` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `editor_images` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `extensions` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `failed_jobs` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `faqs` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `favorites` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `followers` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `footer_links` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `help_articles` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `help_categories` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `home_categories` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `home_sections` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `item_change_logs` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `item_comment_replies` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `item_comment_reports` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `item_comments` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `item_discounts` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `item_histories` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `item_review_replies` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `item_reviews` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `item_updates` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `item_views` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `items` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `jobs` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `kyc_verifications` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `levels` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `mail_templates` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `oauth_providers` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `pages` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `payment_gateways` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `plans` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `playlist_items` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `playlists` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `premium_earnings` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `purchases` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `referral_earnings` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `referrals` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `refresh_tokens` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `refund_replies` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `refunds` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `reviewers` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `sales` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `settings` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `statements` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `storage_providers` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `sub_categories` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `subscriptions` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `support_earnings` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `support_periods` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `testimonials` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `themes` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `ticket_categories` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `ticket_replies` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `ticket_reply_attachments` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `tickets` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `top_nav_links` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `transaction_items` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `transactions` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `translates` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `uploaded_files` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `user_badges` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `user_login_logs` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `users` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `withdrawal_methods` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;
UPDATE `withdrawals` SET `id_new` = UUID() WHERE `id_new` = '' OR `id_new` IS NULL;

-- ── Phase B: Add UUID FK columns and backfill via JOIN ─────
ALTER TABLE `badges` ADD COLUMN `level_id_new` CHAR(36) NULL;
ALTER TABLE `blog_articles` ADD COLUMN `blog_category_id_new` CHAR(36) NULL;
ALTER TABLE `blog_comments` ADD COLUMN `blog_article_id_new` CHAR(36) NULL;
ALTER TABLE `blog_comments` ADD COLUMN `user_id_new` CHAR(36) NULL;
ALTER TABLE `bottom_nav_links` ADD COLUMN `parent_id_new` CHAR(36) NULL;
ALTER TABLE `cart_items` ADD COLUMN `item_id_new` CHAR(36) NULL;
ALTER TABLE `cart_items` ADD COLUMN `support_period_id_new` CHAR(36) NULL;
ALTER TABLE `cart_items` ADD COLUMN `user_id_new` CHAR(36) NULL;
ALTER TABLE `category_options` ADD COLUMN `category_id_new` CHAR(36) NULL;
ALTER TABLE `category_reviewer` ADD COLUMN `category_id_new` CHAR(36) NULL;
ALTER TABLE `category_reviewer` ADD COLUMN `reviewer_id_new` CHAR(36) NULL;
ALTER TABLE `favorites` ADD COLUMN `item_id_new` CHAR(36) NULL;
ALTER TABLE `favorites` ADD COLUMN `user_id_new` CHAR(36) NULL;
ALTER TABLE `followers` ADD COLUMN `follower_id_new` CHAR(36) NULL;
ALTER TABLE `followers` ADD COLUMN `following_id_new` CHAR(36) NULL;
ALTER TABLE `footer_links` ADD COLUMN `parent_id_new` CHAR(36) NULL;
ALTER TABLE `help_articles` ADD COLUMN `help_category_id_new` CHAR(36) NULL;
ALTER TABLE `item_change_logs` ADD COLUMN `item_id_new` CHAR(36) NULL;
ALTER TABLE `item_comment_replies` ADD COLUMN `item_comment_id_new` CHAR(36) NULL;
ALTER TABLE `item_comment_replies` ADD COLUMN `user_id_new` CHAR(36) NULL;
ALTER TABLE `item_comment_reports` ADD COLUMN `item_comment_reply_id_new` CHAR(36) NULL;
ALTER TABLE `item_comment_reports` ADD COLUMN `user_id_new` CHAR(36) NULL;
ALTER TABLE `item_comments` ADD COLUMN `author_id_new` CHAR(36) NULL;
ALTER TABLE `item_comments` ADD COLUMN `item_id_new` CHAR(36) NULL;
ALTER TABLE `item_comments` ADD COLUMN `user_id_new` CHAR(36) NULL;
ALTER TABLE `item_discounts` ADD COLUMN `item_id_new` CHAR(36) NULL;
ALTER TABLE `item_histories` ADD COLUMN `admin_id_new` CHAR(36) NULL;
ALTER TABLE `item_histories` ADD COLUMN `item_id_new` CHAR(36) NULL;
ALTER TABLE `item_histories` ADD COLUMN `reviewer_id_new` CHAR(36) NULL;
ALTER TABLE `item_histories` ADD COLUMN `author_id_new` CHAR(36) NULL;
ALTER TABLE `item_review_replies` ADD COLUMN `item_review_id_new` CHAR(36) NULL;
ALTER TABLE `item_review_replies` ADD COLUMN `user_id_new` CHAR(36) NULL;
ALTER TABLE `item_reviews` ADD COLUMN `author_id_new` CHAR(36) NULL;
ALTER TABLE `item_reviews` ADD COLUMN `item_id_new` CHAR(36) NULL;
ALTER TABLE `item_reviews` ADD COLUMN `user_id_new` CHAR(36) NULL;
ALTER TABLE `item_updates` ADD COLUMN `category_id_new` CHAR(36) NULL;
ALTER TABLE `item_updates` ADD COLUMN `item_id_new` CHAR(36) NULL;
ALTER TABLE `item_updates` ADD COLUMN `sub_category_id_new` CHAR(36) NULL;
ALTER TABLE `item_updates` ADD COLUMN `author_id_new` CHAR(36) NULL;
ALTER TABLE `item_views` ADD COLUMN `item_id_new` CHAR(36) NULL;
ALTER TABLE `items` ADD COLUMN `category_id_new` CHAR(36) NULL;
ALTER TABLE `items` ADD COLUMN `sub_category_id_new` CHAR(36) NULL;
ALTER TABLE `items` ADD COLUMN `author_id_new` CHAR(36) NULL;
ALTER TABLE `kyc_verifications` ADD COLUMN `user_id_new` CHAR(36) NULL;
ALTER TABLE `playlist_items` ADD COLUMN `item_id_new` CHAR(36) NULL;
ALTER TABLE `playlist_items` ADD COLUMN `playlist_id_new` CHAR(36) NULL;
ALTER TABLE `playlists` ADD COLUMN `user_id_new` CHAR(36) NULL;
ALTER TABLE `premium_earnings` ADD COLUMN `author_id_new` CHAR(36) NULL;
ALTER TABLE `premium_earnings` ADD COLUMN `item_id_new` CHAR(36) NULL;
ALTER TABLE `premium_earnings` ADD COLUMN `subscription_id_new` CHAR(36) NULL;
ALTER TABLE `purchases` ADD COLUMN `author_id_new` CHAR(36) NULL;
ALTER TABLE `purchases` ADD COLUMN `item_id_new` CHAR(36) NULL;
ALTER TABLE `purchases` ADD COLUMN `sale_id_new` CHAR(36) NULL;
ALTER TABLE `purchases` ADD COLUMN `user_id_new` CHAR(36) NULL;
ALTER TABLE `referral_earnings` ADD COLUMN `author_id_new` CHAR(36) NULL;
ALTER TABLE `referral_earnings` ADD COLUMN `referral_id_new` CHAR(36) NULL;
ALTER TABLE `referral_earnings` ADD COLUMN `sale_id_new` CHAR(36) NULL;
ALTER TABLE `referrals` ADD COLUMN `author_id_new` CHAR(36) NULL;
ALTER TABLE `referrals` ADD COLUMN `user_id_new` CHAR(36) NULL;
ALTER TABLE `refresh_tokens` ADD COLUMN `user_id_new` CHAR(36) NULL;
ALTER TABLE `refund_replies` ADD COLUMN `refund_id_new` CHAR(36) NULL;
ALTER TABLE `refund_replies` ADD COLUMN `user_id_new` CHAR(36) NULL;
ALTER TABLE `refunds` ADD COLUMN `author_id_new` CHAR(36) NULL;
ALTER TABLE `refunds` ADD COLUMN `purchase_id_new` CHAR(36) NULL;
ALTER TABLE `refunds` ADD COLUMN `user_id_new` CHAR(36) NULL;
ALTER TABLE `sales` ADD COLUMN `author_id_new` CHAR(36) NULL;
ALTER TABLE `sales` ADD COLUMN `item_id_new` CHAR(36) NULL;
ALTER TABLE `sales` ADD COLUMN `user_id_new` CHAR(36) NULL;
ALTER TABLE `statements` ADD COLUMN `user_id_new` CHAR(36) NULL;
ALTER TABLE `sub_categories` ADD COLUMN `category_id_new` CHAR(36) NULL;
ALTER TABLE `subscriptions` ADD COLUMN `plan_id_new` CHAR(36) NULL;
ALTER TABLE `subscriptions` ADD COLUMN `user_id_new` CHAR(36) NULL;
ALTER TABLE `support_earnings` ADD COLUMN `author_id_new` CHAR(36) NULL;
ALTER TABLE `support_earnings` ADD COLUMN `purchase_id_new` CHAR(36) NULL;
ALTER TABLE `ticket_replies` ADD COLUMN `admin_id_new` CHAR(36) NULL;
ALTER TABLE `ticket_replies` ADD COLUMN `ticket_id_new` CHAR(36) NULL;
ALTER TABLE `ticket_replies` ADD COLUMN `user_id_new` CHAR(36) NULL;
ALTER TABLE `ticket_reply_attachments` ADD COLUMN `ticket_reply_id_new` CHAR(36) NULL;
ALTER TABLE `tickets` ADD COLUMN `ticket_category_id_new` CHAR(36) NULL;
ALTER TABLE `tickets` ADD COLUMN `user_id_new` CHAR(36) NULL;
ALTER TABLE `top_nav_links` ADD COLUMN `parent_id_new` CHAR(36) NULL;
ALTER TABLE `transaction_items` ADD COLUMN `item_id_new` CHAR(36) NULL;
ALTER TABLE `transaction_items` ADD COLUMN `transaction_id_new` CHAR(36) NULL;
ALTER TABLE `transactions` ADD COLUMN `payment_gateway_id_new` CHAR(36) NULL;
ALTER TABLE `transactions` ADD COLUMN `plan_id_new` CHAR(36) NULL;
ALTER TABLE `transactions` ADD COLUMN `purchase_id_new` CHAR(36) NULL;
ALTER TABLE `transactions` ADD COLUMN `user_id_new` CHAR(36) NULL;
ALTER TABLE `uploaded_files` ADD COLUMN `category_id_new` CHAR(36) NULL;
ALTER TABLE `uploaded_files` ADD COLUMN `author_id_new` CHAR(36) NULL;
ALTER TABLE `user_badges` ADD COLUMN `badge_id_new` CHAR(36) NULL;
ALTER TABLE `user_badges` ADD COLUMN `user_id_new` CHAR(36) NULL;
ALTER TABLE `user_login_logs` ADD COLUMN `user_id_new` CHAR(36) NULL;
ALTER TABLE `users` ADD COLUMN `level_id_new` CHAR(36) NULL;
ALTER TABLE `users` ADD COLUMN `withdrawal_method_id_new` CHAR(36) NULL;
ALTER TABLE `withdrawals` ADD COLUMN `author_id_new` CHAR(36) NULL;

UPDATE `badges` t JOIN `levels` r ON t.`level_id` = r.`id` SET t.`level_id_new` = r.`id_new`;
UPDATE `blog_articles` t JOIN `blog_categories` r ON t.`blog_category_id` = r.`id` SET t.`blog_category_id_new` = r.`id_new`;
UPDATE `blog_comments` t JOIN `blog_articles` r ON t.`blog_article_id` = r.`id` SET t.`blog_article_id_new` = r.`id_new`;
UPDATE `blog_comments` t JOIN `users` r ON t.`user_id` = r.`id` SET t.`user_id_new` = r.`id_new`;
UPDATE `bottom_nav_links` t JOIN `bottom_nav_links` r ON t.`parent_id` = r.`id` SET t.`parent_id_new` = r.`id_new`;
UPDATE `cart_items` t JOIN `items` r ON t.`item_id` = r.`id` SET t.`item_id_new` = r.`id_new`;
UPDATE `cart_items` t JOIN `support_periods` r ON t.`support_period_id` = r.`id` SET t.`support_period_id_new` = r.`id_new`;
UPDATE `cart_items` t JOIN `users` r ON t.`user_id` = r.`id` SET t.`user_id_new` = r.`id_new`;
UPDATE `category_options` t JOIN `categories` r ON t.`category_id` = r.`id` SET t.`category_id_new` = r.`id_new`;
UPDATE `category_reviewer` t JOIN `categories` r ON t.`category_id` = r.`id` SET t.`category_id_new` = r.`id_new`;
UPDATE `category_reviewer` t JOIN `reviewers` r ON t.`reviewer_id` = r.`id` SET t.`reviewer_id_new` = r.`id_new`;
UPDATE `favorites` t JOIN `items` r ON t.`item_id` = r.`id` SET t.`item_id_new` = r.`id_new`;
UPDATE `favorites` t JOIN `users` r ON t.`user_id` = r.`id` SET t.`user_id_new` = r.`id_new`;
UPDATE `followers` t JOIN `users` r ON t.`follower_id` = r.`id` SET t.`follower_id_new` = r.`id_new`;
UPDATE `followers` t JOIN `users` r ON t.`following_id` = r.`id` SET t.`following_id_new` = r.`id_new`;
UPDATE `footer_links` t JOIN `footer_links` r ON t.`parent_id` = r.`id` SET t.`parent_id_new` = r.`id_new`;
UPDATE `help_articles` t JOIN `help_categories` r ON t.`help_category_id` = r.`id` SET t.`help_category_id_new` = r.`id_new`;
UPDATE `item_change_logs` t JOIN `items` r ON t.`item_id` = r.`id` SET t.`item_id_new` = r.`id_new`;
UPDATE `item_comment_replies` t JOIN `item_comments` r ON t.`item_comment_id` = r.`id` SET t.`item_comment_id_new` = r.`id_new`;
UPDATE `item_comment_replies` t JOIN `users` r ON t.`user_id` = r.`id` SET t.`user_id_new` = r.`id_new`;
UPDATE `item_comment_reports` t JOIN `item_comment_replies` r ON t.`item_comment_reply_id` = r.`id` SET t.`item_comment_reply_id_new` = r.`id_new`;
UPDATE `item_comment_reports` t JOIN `users` r ON t.`user_id` = r.`id` SET t.`user_id_new` = r.`id_new`;
UPDATE `item_comments` t JOIN `users` r ON t.`author_id` = r.`id` SET t.`author_id_new` = r.`id_new`;
UPDATE `item_comments` t JOIN `items` r ON t.`item_id` = r.`id` SET t.`item_id_new` = r.`id_new`;
UPDATE `item_comments` t JOIN `users` r ON t.`user_id` = r.`id` SET t.`user_id_new` = r.`id_new`;
UPDATE `item_discounts` t JOIN `items` r ON t.`item_id` = r.`id` SET t.`item_id_new` = r.`id_new`;
UPDATE `item_histories` t JOIN `admins` r ON t.`admin_id` = r.`id` SET t.`admin_id_new` = r.`id_new`;
UPDATE `item_histories` t JOIN `items` r ON t.`item_id` = r.`id` SET t.`item_id_new` = r.`id_new`;
UPDATE `item_histories` t JOIN `reviewers` r ON t.`reviewer_id` = r.`id` SET t.`reviewer_id_new` = r.`id_new`;
UPDATE `item_histories` t JOIN `users` r ON t.`author_id` = r.`id` SET t.`author_id_new` = r.`id_new`;
UPDATE `item_review_replies` t JOIN `item_reviews` r ON t.`item_review_id` = r.`id` SET t.`item_review_id_new` = r.`id_new`;
UPDATE `item_review_replies` t JOIN `users` r ON t.`user_id` = r.`id` SET t.`user_id_new` = r.`id_new`;
UPDATE `item_reviews` t JOIN `users` r ON t.`author_id` = r.`id` SET t.`author_id_new` = r.`id_new`;
UPDATE `item_reviews` t JOIN `items` r ON t.`item_id` = r.`id` SET t.`item_id_new` = r.`id_new`;
UPDATE `item_reviews` t JOIN `users` r ON t.`user_id` = r.`id` SET t.`user_id_new` = r.`id_new`;
UPDATE `item_updates` t JOIN `categories` r ON t.`category_id` = r.`id` SET t.`category_id_new` = r.`id_new`;
UPDATE `item_updates` t JOIN `items` r ON t.`item_id` = r.`id` SET t.`item_id_new` = r.`id_new`;
UPDATE `item_updates` t JOIN `sub_categories` r ON t.`sub_category_id` = r.`id` SET t.`sub_category_id_new` = r.`id_new`;
UPDATE `item_updates` t JOIN `users` r ON t.`author_id` = r.`id` SET t.`author_id_new` = r.`id_new`;
UPDATE `item_views` t JOIN `items` r ON t.`item_id` = r.`id` SET t.`item_id_new` = r.`id_new`;
UPDATE `items` t JOIN `categories` r ON t.`category_id` = r.`id` SET t.`category_id_new` = r.`id_new`;
UPDATE `items` t JOIN `sub_categories` r ON t.`sub_category_id` = r.`id` SET t.`sub_category_id_new` = r.`id_new`;
UPDATE `items` t JOIN `users` r ON t.`author_id` = r.`id` SET t.`author_id_new` = r.`id_new`;
UPDATE `kyc_verifications` t JOIN `users` r ON t.`user_id` = r.`id` SET t.`user_id_new` = r.`id_new`;
UPDATE `playlist_items` t JOIN `items` r ON t.`item_id` = r.`id` SET t.`item_id_new` = r.`id_new`;
UPDATE `playlist_items` t JOIN `playlists` r ON t.`playlist_id` = r.`id` SET t.`playlist_id_new` = r.`id_new`;
UPDATE `playlists` t JOIN `users` r ON t.`user_id` = r.`id` SET t.`user_id_new` = r.`id_new`;
UPDATE `premium_earnings` t JOIN `users` r ON t.`author_id` = r.`id` SET t.`author_id_new` = r.`id_new`;
UPDATE `premium_earnings` t JOIN `items` r ON t.`item_id` = r.`id` SET t.`item_id_new` = r.`id_new`;
UPDATE `premium_earnings` t JOIN `subscriptions` r ON t.`subscription_id` = r.`id` SET t.`subscription_id_new` = r.`id_new`;
UPDATE `purchases` t JOIN `users` r ON t.`author_id` = r.`id` SET t.`author_id_new` = r.`id_new`;
UPDATE `purchases` t JOIN `items` r ON t.`item_id` = r.`id` SET t.`item_id_new` = r.`id_new`;
UPDATE `purchases` t JOIN `sales` r ON t.`sale_id` = r.`id` SET t.`sale_id_new` = r.`id_new`;
UPDATE `purchases` t JOIN `users` r ON t.`user_id` = r.`id` SET t.`user_id_new` = r.`id_new`;
UPDATE `referral_earnings` t JOIN `users` r ON t.`author_id` = r.`id` SET t.`author_id_new` = r.`id_new`;
UPDATE `referral_earnings` t JOIN `referrals` r ON t.`referral_id` = r.`id` SET t.`referral_id_new` = r.`id_new`;
UPDATE `referral_earnings` t JOIN `sales` r ON t.`sale_id` = r.`id` SET t.`sale_id_new` = r.`id_new`;
UPDATE `referrals` t JOIN `users` r ON t.`author_id` = r.`id` SET t.`author_id_new` = r.`id_new`;
UPDATE `referrals` t JOIN `users` r ON t.`user_id` = r.`id` SET t.`user_id_new` = r.`id_new`;
UPDATE `refresh_tokens` t JOIN `users` r ON t.`user_id` = r.`id` SET t.`user_id_new` = r.`id_new`;
UPDATE `refund_replies` t JOIN `refunds` r ON t.`refund_id` = r.`id` SET t.`refund_id_new` = r.`id_new`;
UPDATE `refund_replies` t JOIN `users` r ON t.`user_id` = r.`id` SET t.`user_id_new` = r.`id_new`;
UPDATE `refunds` t JOIN `users` r ON t.`author_id` = r.`id` SET t.`author_id_new` = r.`id_new`;
UPDATE `refunds` t JOIN `purchases` r ON t.`purchase_id` = r.`id` SET t.`purchase_id_new` = r.`id_new`;
UPDATE `refunds` t JOIN `users` r ON t.`user_id` = r.`id` SET t.`user_id_new` = r.`id_new`;
UPDATE `sales` t JOIN `users` r ON t.`author_id` = r.`id` SET t.`author_id_new` = r.`id_new`;
UPDATE `sales` t JOIN `items` r ON t.`item_id` = r.`id` SET t.`item_id_new` = r.`id_new`;
UPDATE `sales` t JOIN `users` r ON t.`user_id` = r.`id` SET t.`user_id_new` = r.`id_new`;
UPDATE `statements` t JOIN `users` r ON t.`user_id` = r.`id` SET t.`user_id_new` = r.`id_new`;
UPDATE `sub_categories` t JOIN `categories` r ON t.`category_id` = r.`id` SET t.`category_id_new` = r.`id_new`;
UPDATE `subscriptions` t JOIN `plans` r ON t.`plan_id` = r.`id` SET t.`plan_id_new` = r.`id_new`;
UPDATE `subscriptions` t JOIN `users` r ON t.`user_id` = r.`id` SET t.`user_id_new` = r.`id_new`;
UPDATE `support_earnings` t JOIN `users` r ON t.`author_id` = r.`id` SET t.`author_id_new` = r.`id_new`;
UPDATE `support_earnings` t JOIN `purchases` r ON t.`purchase_id` = r.`id` SET t.`purchase_id_new` = r.`id_new`;
UPDATE `ticket_replies` t JOIN `admins` r ON t.`admin_id` = r.`id` SET t.`admin_id_new` = r.`id_new`;
UPDATE `ticket_replies` t JOIN `tickets` r ON t.`ticket_id` = r.`id` SET t.`ticket_id_new` = r.`id_new`;
UPDATE `ticket_replies` t JOIN `users` r ON t.`user_id` = r.`id` SET t.`user_id_new` = r.`id_new`;
UPDATE `ticket_reply_attachments` t JOIN `ticket_replies` r ON t.`ticket_reply_id` = r.`id` SET t.`ticket_reply_id_new` = r.`id_new`;
UPDATE `tickets` t JOIN `ticket_categories` r ON t.`ticket_category_id` = r.`id` SET t.`ticket_category_id_new` = r.`id_new`;
UPDATE `tickets` t JOIN `users` r ON t.`user_id` = r.`id` SET t.`user_id_new` = r.`id_new`;
UPDATE `top_nav_links` t JOIN `top_nav_links` r ON t.`parent_id` = r.`id` SET t.`parent_id_new` = r.`id_new`;
UPDATE `transaction_items` t JOIN `items` r ON t.`item_id` = r.`id` SET t.`item_id_new` = r.`id_new`;
UPDATE `transaction_items` t JOIN `transactions` r ON t.`transaction_id` = r.`id` SET t.`transaction_id_new` = r.`id_new`;
UPDATE `transactions` t JOIN `payment_gateways` r ON t.`payment_gateway_id` = r.`id` SET t.`payment_gateway_id_new` = r.`id_new`;
UPDATE `transactions` t JOIN `plans` r ON t.`plan_id` = r.`id` SET t.`plan_id_new` = r.`id_new`;
UPDATE `transactions` t JOIN `purchases` r ON t.`purchase_id` = r.`id` SET t.`purchase_id_new` = r.`id_new`;
UPDATE `transactions` t JOIN `users` r ON t.`user_id` = r.`id` SET t.`user_id_new` = r.`id_new`;
UPDATE `uploaded_files` t JOIN `categories` r ON t.`category_id` = r.`id` SET t.`category_id_new` = r.`id_new`;
UPDATE `uploaded_files` t JOIN `users` r ON t.`author_id` = r.`id` SET t.`author_id_new` = r.`id_new`;
UPDATE `user_badges` t JOIN `badges` r ON t.`badge_id` = r.`id` SET t.`badge_id_new` = r.`id_new`;
UPDATE `user_badges` t JOIN `users` r ON t.`user_id` = r.`id` SET t.`user_id_new` = r.`id_new`;
UPDATE `user_login_logs` t JOIN `users` r ON t.`user_id` = r.`id` SET t.`user_id_new` = r.`id_new`;
UPDATE `users` t JOIN `levels` r ON t.`level_id` = r.`id` SET t.`level_id_new` = r.`id_new`;
UPDATE `users` t JOIN `withdrawal_methods` r ON t.`withdrawal_method_id` = r.`id` SET t.`withdrawal_method_id_new` = r.`id_new`;
UPDATE `withdrawals` t JOIN `users` r ON t.`author_id` = r.`id` SET t.`author_id_new` = r.`id_new`;

-- ── Phase C: Drop FK constraints ───────────────────────────
ALTER TABLE `badges` DROP FOREIGN KEY `badges_level_id_foreign`;
ALTER TABLE `blog_articles` DROP FOREIGN KEY `blog_articles_blog_category_id_foreign`;
ALTER TABLE `blog_comments` DROP FOREIGN KEY `blog_comments_blog_article_id_foreign`;
ALTER TABLE `blog_comments` DROP FOREIGN KEY `blog_comments_user_id_foreign`;
ALTER TABLE `bottom_nav_links` DROP FOREIGN KEY `bottom_nav_links_parent_id_foreign`;
ALTER TABLE `cart_items` DROP FOREIGN KEY `cart_items_item_id_foreign`;
ALTER TABLE `cart_items` DROP FOREIGN KEY `cart_items_support_period_id_foreign`;
ALTER TABLE `cart_items` DROP FOREIGN KEY `cart_items_user_id_foreign`;
ALTER TABLE `category_options` DROP FOREIGN KEY `category_options_category_id_foreign`;
ALTER TABLE `category_reviewer` DROP FOREIGN KEY `category_reviewer_category_id_foreign`;
ALTER TABLE `category_reviewer` DROP FOREIGN KEY `category_reviewer_reviewer_id_foreign`;
ALTER TABLE `favorites` DROP FOREIGN KEY `favorites_item_id_foreign`;
ALTER TABLE `favorites` DROP FOREIGN KEY `favorites_user_id_foreign`;
ALTER TABLE `followers` DROP FOREIGN KEY `followers_follower_id_foreign`;
ALTER TABLE `followers` DROP FOREIGN KEY `followers_following_id_foreign`;
ALTER TABLE `footer_links` DROP FOREIGN KEY `footer_links_parent_id_foreign`;
ALTER TABLE `help_articles` DROP FOREIGN KEY `help_articles_help_category_id_foreign`;
ALTER TABLE `item_change_logs` DROP FOREIGN KEY `item_change_logs_item_id_foreign`;
ALTER TABLE `item_comment_replies` DROP FOREIGN KEY `item_comment_replies_item_comment_id_foreign`;
ALTER TABLE `item_comment_replies` DROP FOREIGN KEY `item_comment_replies_user_id_foreign`;
ALTER TABLE `item_comment_reports` DROP FOREIGN KEY `item_comment_reports_item_comment_reply_id_foreign`;
ALTER TABLE `item_comment_reports` DROP FOREIGN KEY `item_comment_reports_user_id_foreign`;
ALTER TABLE `item_comments` DROP FOREIGN KEY `item_comments_author_id_foreign`;
ALTER TABLE `item_comments` DROP FOREIGN KEY `item_comments_item_id_foreign`;
ALTER TABLE `item_comments` DROP FOREIGN KEY `item_comments_user_id_foreign`;
ALTER TABLE `item_discounts` DROP FOREIGN KEY `item_discounts_item_id_foreign`;
ALTER TABLE `item_histories` DROP FOREIGN KEY `item_histories_admin_id_foreign`;
ALTER TABLE `item_histories` DROP FOREIGN KEY `item_histories_item_id_foreign`;
ALTER TABLE `item_histories` DROP FOREIGN KEY `item_histories_reviewer_id_foreign`;
ALTER TABLE `item_histories` DROP FOREIGN KEY `item_histories_user_id_foreign`;
ALTER TABLE `item_review_replies` DROP FOREIGN KEY `item_review_replies_item_review_id_foreign`;
ALTER TABLE `item_review_replies` DROP FOREIGN KEY `item_review_replies_user_id_foreign`;
ALTER TABLE `item_reviews` DROP FOREIGN KEY `item_reviews_author_id_foreign`;
ALTER TABLE `item_reviews` DROP FOREIGN KEY `item_reviews_item_id_foreign`;
ALTER TABLE `item_reviews` DROP FOREIGN KEY `item_reviews_user_id_foreign`;
ALTER TABLE `item_updates` DROP FOREIGN KEY `item_updates_category_id_foreign`;
ALTER TABLE `item_updates` DROP FOREIGN KEY `item_updates_item_id_foreign`;
ALTER TABLE `item_updates` DROP FOREIGN KEY `item_updates_sub_category_id_foreign`;
ALTER TABLE `item_updates` DROP FOREIGN KEY `item_updates_user_id_foreign`;
ALTER TABLE `item_views` DROP FOREIGN KEY `item_views_item_id_foreign`;
ALTER TABLE `items` DROP FOREIGN KEY `items_category_id_foreign`;
ALTER TABLE `items` DROP FOREIGN KEY `items_sub_category_id_foreign`;
ALTER TABLE `items` DROP FOREIGN KEY `items_user_id_foreign`;
ALTER TABLE `kyc_verifications` DROP FOREIGN KEY `kyc_verifications_user_id_foreign`;
ALTER TABLE `playlist_items` DROP FOREIGN KEY `playlist_items_item_id_fkey`;
ALTER TABLE `playlist_items` DROP FOREIGN KEY `playlist_items_playlist_id_fkey`;
ALTER TABLE `playlists` DROP FOREIGN KEY `playlists_user_id_fkey`;
ALTER TABLE `premium_earnings` DROP FOREIGN KEY `premium_earnings_author_id_foreign`;
ALTER TABLE `premium_earnings` DROP FOREIGN KEY `premium_earnings_item_id_foreign`;
ALTER TABLE `premium_earnings` DROP FOREIGN KEY `premium_earnings_subscription_id_foreign`;
ALTER TABLE `purchases` DROP FOREIGN KEY `purchases_author_id_foreign`;
ALTER TABLE `purchases` DROP FOREIGN KEY `purchases_item_id_foreign`;
ALTER TABLE `purchases` DROP FOREIGN KEY `purchases_sale_id_foreign`;
ALTER TABLE `purchases` DROP FOREIGN KEY `purchases_user_id_foreign`;
ALTER TABLE `referral_earnings` DROP FOREIGN KEY `referral_earnings_author_id_foreign`;
ALTER TABLE `referral_earnings` DROP FOREIGN KEY `referral_earnings_referral_id_foreign`;
ALTER TABLE `referral_earnings` DROP FOREIGN KEY `referral_earnings_sale_id_foreign`;
ALTER TABLE `referrals` DROP FOREIGN KEY `referrals_author_id_foreign`;
ALTER TABLE `referrals` DROP FOREIGN KEY `referrals_user_id_foreign`;
ALTER TABLE `refresh_tokens` DROP FOREIGN KEY `refresh_tokens_user_id_fkey`;
ALTER TABLE `refund_replies` DROP FOREIGN KEY `refund_replies_refund_id_foreign`;
ALTER TABLE `refund_replies` DROP FOREIGN KEY `refund_replies_user_id_foreign`;
ALTER TABLE `refunds` DROP FOREIGN KEY `refunds_author_id_foreign`;
ALTER TABLE `refunds` DROP FOREIGN KEY `refunds_purchase_id_foreign`;
ALTER TABLE `refunds` DROP FOREIGN KEY `refunds_user_id_foreign`;
ALTER TABLE `sales` DROP FOREIGN KEY `sales_author_id_foreign`;
ALTER TABLE `sales` DROP FOREIGN KEY `sales_item_id_foreign`;
ALTER TABLE `sales` DROP FOREIGN KEY `sales_user_id_foreign`;
ALTER TABLE `statements` DROP FOREIGN KEY `statements_user_id_foreign`;
ALTER TABLE `sub_categories` DROP FOREIGN KEY `sub_categories_category_id_foreign`;
ALTER TABLE `subscriptions` DROP FOREIGN KEY `subscriptions_plan_id_foreign`;
ALTER TABLE `subscriptions` DROP FOREIGN KEY `subscriptions_user_id_foreign`;
ALTER TABLE `support_earnings` DROP FOREIGN KEY `support_earnings_author_id_foreign`;
ALTER TABLE `support_earnings` DROP FOREIGN KEY `support_earnings_purchase_id_foreign`;
ALTER TABLE `ticket_replies` DROP FOREIGN KEY `ticket_replies_admin_id_foreign`;
ALTER TABLE `ticket_replies` DROP FOREIGN KEY `ticket_replies_ticket_id_foreign`;
ALTER TABLE `ticket_replies` DROP FOREIGN KEY `ticket_replies_user_id_foreign`;
ALTER TABLE `ticket_reply_attachments` DROP FOREIGN KEY `ticket_reply_attachments_ticket_reply_id_foreign`;
ALTER TABLE `tickets` DROP FOREIGN KEY `tickets_ticket_category_id_foreign`;
ALTER TABLE `tickets` DROP FOREIGN KEY `tickets_user_id_foreign`;
ALTER TABLE `top_nav_links` DROP FOREIGN KEY `top_nav_links_parent_id_foreign`;
ALTER TABLE `transaction_items` DROP FOREIGN KEY `transaction_items_item_id_foreign`;
ALTER TABLE `transaction_items` DROP FOREIGN KEY `transaction_items_transaction_id_foreign`;
ALTER TABLE `transactions` DROP FOREIGN KEY `transactions_payment_gateway_id_foreign`;
ALTER TABLE `transactions` DROP FOREIGN KEY `transactions_plan_id_foreign`;
ALTER TABLE `transactions` DROP FOREIGN KEY `transactions_purchase_id_foreign`;
ALTER TABLE `transactions` DROP FOREIGN KEY `transactions_user_id_foreign`;
ALTER TABLE `uploaded_files` DROP FOREIGN KEY `uploaded_files_category_id_foreign`;
ALTER TABLE `uploaded_files` DROP FOREIGN KEY `uploaded_files_user_id_foreign`;
ALTER TABLE `user_badges` DROP FOREIGN KEY `user_badges_badge_id_foreign`;
ALTER TABLE `user_badges` DROP FOREIGN KEY `user_badges_user_id_foreign`;
ALTER TABLE `user_login_logs` DROP FOREIGN KEY `user_login_logs_user_id_foreign`;
ALTER TABLE `users` DROP FOREIGN KEY `users_level_id_foreign`;
ALTER TABLE `users` DROP FOREIGN KEY `users_withdrawal_method_id_foreign`;
ALTER TABLE `withdrawals` DROP FOREIGN KEY `withdrawals_user_id_foreign`;

-- ── Phase D: Drop old PK columns, swap in UUID PKs ─────────
ALTER TABLE `addons` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `admin_notifications` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `admins` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `ads` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `author_taxes` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `badges` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `blog_articles` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `blog_categories` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `blog_comments` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `bottom_nav_links` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `buyer_taxes` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `captcha_providers` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `cart_items` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `categories` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `category_options` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `category_reviewer` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `currencies` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `editor_images` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `extensions` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `failed_jobs` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `faqs` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `favorites` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `followers` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `footer_links` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `help_articles` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `help_categories` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `home_categories` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `home_sections` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `item_change_logs` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `item_comment_replies` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `item_comment_reports` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `item_comments` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `item_discounts` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `item_histories` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `item_review_replies` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `item_reviews` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `item_updates` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `item_views` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `items` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `jobs` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `kyc_verifications` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `levels` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `mail_templates` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `oauth_providers` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `pages` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `payment_gateways` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `plans` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `playlist_items` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `playlists` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `premium_earnings` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `purchases` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `referral_earnings` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `referrals` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `refresh_tokens` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `refund_replies` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `refunds` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `reviewers` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `sales` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `settings` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `statements` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `storage_providers` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `sub_categories` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `subscriptions` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `support_earnings` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `support_periods` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `testimonials` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `themes` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `ticket_categories` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `ticket_replies` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `ticket_reply_attachments` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `tickets` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `top_nav_links` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `transaction_items` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `transactions` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `translates` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `uploaded_files` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `user_badges` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `user_login_logs` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `users` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `withdrawal_methods` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);
ALTER TABLE `withdrawals` DROP PRIMARY KEY, DROP COLUMN `id`, CHANGE `id_new` `id` CHAR(36) NOT NULL, ADD PRIMARY KEY (`id`);

-- ── Phase D: Drop old FK columns, swap in UUID FK columns ──
ALTER TABLE `badges` DROP COLUMN `level_id`, CHANGE `level_id_new` `level_id` CHAR(36) NULL;
ALTER TABLE `blog_articles` DROP COLUMN `blog_category_id`, CHANGE `blog_category_id_new` `blog_category_id` CHAR(36) NOT NULL;
ALTER TABLE `blog_comments` DROP COLUMN `blog_article_id`, CHANGE `blog_article_id_new` `blog_article_id` CHAR(36) NOT NULL;
ALTER TABLE `blog_comments` DROP COLUMN `user_id`, CHANGE `user_id_new` `user_id` CHAR(36) NULL;
ALTER TABLE `bottom_nav_links` DROP COLUMN `parent_id`, CHANGE `parent_id_new` `parent_id` CHAR(36) NULL;
ALTER TABLE `cart_items` DROP COLUMN `item_id`, CHANGE `item_id_new` `item_id` CHAR(36) NOT NULL;
ALTER TABLE `cart_items` DROP COLUMN `support_period_id`, CHANGE `support_period_id_new` `support_period_id` CHAR(36) NULL;
ALTER TABLE `cart_items` DROP COLUMN `user_id`, CHANGE `user_id_new` `user_id` CHAR(36) NULL;
ALTER TABLE `category_options` DROP COLUMN `category_id`, CHANGE `category_id_new` `category_id` CHAR(36) NOT NULL;
ALTER TABLE `category_reviewer` DROP COLUMN `category_id`, CHANGE `category_id_new` `category_id` CHAR(36) NOT NULL;
ALTER TABLE `category_reviewer` DROP COLUMN `reviewer_id`, CHANGE `reviewer_id_new` `reviewer_id` CHAR(36) NOT NULL;
ALTER TABLE `favorites` DROP COLUMN `item_id`, CHANGE `item_id_new` `item_id` CHAR(36) NOT NULL;
ALTER TABLE `favorites` DROP COLUMN `user_id`, CHANGE `user_id_new` `user_id` CHAR(36) NOT NULL;
ALTER TABLE `followers` DROP COLUMN `follower_id`, CHANGE `follower_id_new` `follower_id` CHAR(36) NOT NULL;
ALTER TABLE `followers` DROP COLUMN `following_id`, CHANGE `following_id_new` `following_id` CHAR(36) NOT NULL;
ALTER TABLE `footer_links` DROP COLUMN `parent_id`, CHANGE `parent_id_new` `parent_id` CHAR(36) NULL;
ALTER TABLE `help_articles` DROP COLUMN `help_category_id`, CHANGE `help_category_id_new` `help_category_id` CHAR(36) NOT NULL;
ALTER TABLE `item_change_logs` DROP COLUMN `item_id`, CHANGE `item_id_new` `item_id` CHAR(36) NOT NULL;
ALTER TABLE `item_comment_replies` DROP COLUMN `item_comment_id`, CHANGE `item_comment_id_new` `item_comment_id` CHAR(36) NOT NULL;
ALTER TABLE `item_comment_replies` DROP COLUMN `user_id`, CHANGE `user_id_new` `user_id` CHAR(36) NOT NULL;
ALTER TABLE `item_comment_reports` DROP COLUMN `item_comment_reply_id`, CHANGE `item_comment_reply_id_new` `item_comment_reply_id` CHAR(36) NOT NULL;
ALTER TABLE `item_comment_reports` DROP COLUMN `user_id`, CHANGE `user_id_new` `user_id` CHAR(36) NOT NULL;
ALTER TABLE `item_comments` DROP COLUMN `author_id`, CHANGE `author_id_new` `author_id` CHAR(36) NOT NULL;
ALTER TABLE `item_comments` DROP COLUMN `item_id`, CHANGE `item_id_new` `item_id` CHAR(36) NOT NULL;
ALTER TABLE `item_comments` DROP COLUMN `user_id`, CHANGE `user_id_new` `user_id` CHAR(36) NOT NULL;
ALTER TABLE `item_discounts` DROP COLUMN `item_id`, CHANGE `item_id_new` `item_id` CHAR(36) NOT NULL;
ALTER TABLE `item_histories` DROP COLUMN `admin_id`, CHANGE `admin_id_new` `admin_id` CHAR(36) NULL;
ALTER TABLE `item_histories` DROP COLUMN `item_id`, CHANGE `item_id_new` `item_id` CHAR(36) NOT NULL;
ALTER TABLE `item_histories` DROP COLUMN `reviewer_id`, CHANGE `reviewer_id_new` `reviewer_id` CHAR(36) NULL;
ALTER TABLE `item_histories` DROP COLUMN `author_id`, CHANGE `author_id_new` `author_id` CHAR(36) NULL;
ALTER TABLE `item_review_replies` DROP COLUMN `item_review_id`, CHANGE `item_review_id_new` `item_review_id` CHAR(36) NOT NULL;
ALTER TABLE `item_review_replies` DROP COLUMN `user_id`, CHANGE `user_id_new` `user_id` CHAR(36) NOT NULL;
ALTER TABLE `item_reviews` DROP COLUMN `author_id`, CHANGE `author_id_new` `author_id` CHAR(36) NOT NULL;
ALTER TABLE `item_reviews` DROP COLUMN `item_id`, CHANGE `item_id_new` `item_id` CHAR(36) NOT NULL;
ALTER TABLE `item_reviews` DROP COLUMN `user_id`, CHANGE `user_id_new` `user_id` CHAR(36) NOT NULL;
ALTER TABLE `item_updates` DROP COLUMN `category_id`, CHANGE `category_id_new` `category_id` CHAR(36) NOT NULL;
ALTER TABLE `item_updates` DROP COLUMN `item_id`, CHANGE `item_id_new` `item_id` CHAR(36) NOT NULL;
ALTER TABLE `item_updates` DROP COLUMN `sub_category_id`, CHANGE `sub_category_id_new` `sub_category_id` CHAR(36) NULL;
ALTER TABLE `item_updates` DROP COLUMN `author_id`, CHANGE `author_id_new` `author_id` CHAR(36) NOT NULL;
ALTER TABLE `item_views` DROP COLUMN `item_id`, CHANGE `item_id_new` `item_id` CHAR(36) NOT NULL;
ALTER TABLE `items` DROP COLUMN `category_id`, CHANGE `category_id_new` `category_id` CHAR(36) NOT NULL;
ALTER TABLE `items` DROP COLUMN `sub_category_id`, CHANGE `sub_category_id_new` `sub_category_id` CHAR(36) NULL;
ALTER TABLE `items` DROP COLUMN `author_id`, CHANGE `author_id_new` `author_id` CHAR(36) NOT NULL;
ALTER TABLE `kyc_verifications` DROP COLUMN `user_id`, CHANGE `user_id_new` `user_id` CHAR(36) NOT NULL;
ALTER TABLE `playlist_items` DROP COLUMN `item_id`, CHANGE `item_id_new` `item_id` CHAR(36) NOT NULL;
ALTER TABLE `playlist_items` DROP COLUMN `playlist_id`, CHANGE `playlist_id_new` `playlist_id` CHAR(36) NOT NULL;
ALTER TABLE `playlists` DROP COLUMN `user_id`, CHANGE `user_id_new` `user_id` CHAR(36) NOT NULL;
ALTER TABLE `premium_earnings` DROP COLUMN `author_id`, CHANGE `author_id_new` `author_id` CHAR(36) NOT NULL;
ALTER TABLE `premium_earnings` DROP COLUMN `item_id`, CHANGE `item_id_new` `item_id` CHAR(36) NULL;
ALTER TABLE `premium_earnings` DROP COLUMN `subscription_id`, CHANGE `subscription_id_new` `subscription_id` CHAR(36) NULL;
ALTER TABLE `purchases` DROP COLUMN `author_id`, CHANGE `author_id_new` `author_id` CHAR(36) NOT NULL;
ALTER TABLE `purchases` DROP COLUMN `item_id`, CHANGE `item_id_new` `item_id` CHAR(36) NOT NULL;
ALTER TABLE `purchases` DROP COLUMN `sale_id`, CHANGE `sale_id_new` `sale_id` CHAR(36) NOT NULL;
ALTER TABLE `purchases` DROP COLUMN `user_id`, CHANGE `user_id_new` `user_id` CHAR(36) NOT NULL;
ALTER TABLE `referral_earnings` DROP COLUMN `author_id`, CHANGE `author_id_new` `author_id` CHAR(36) NOT NULL;
ALTER TABLE `referral_earnings` DROP COLUMN `referral_id`, CHANGE `referral_id_new` `referral_id` CHAR(36) NOT NULL;
ALTER TABLE `referral_earnings` DROP COLUMN `sale_id`, CHANGE `sale_id_new` `sale_id` CHAR(36) NOT NULL;
ALTER TABLE `referrals` DROP COLUMN `author_id`, CHANGE `author_id_new` `author_id` CHAR(36) NOT NULL;
ALTER TABLE `referrals` DROP COLUMN `user_id`, CHANGE `user_id_new` `user_id` CHAR(36) NOT NULL;
ALTER TABLE `refresh_tokens` DROP COLUMN `user_id`, CHANGE `user_id_new` `user_id` CHAR(36) NOT NULL;
ALTER TABLE `refund_replies` DROP COLUMN `refund_id`, CHANGE `refund_id_new` `refund_id` CHAR(36) NOT NULL;
ALTER TABLE `refund_replies` DROP COLUMN `user_id`, CHANGE `user_id_new` `user_id` CHAR(36) NOT NULL;
ALTER TABLE `refunds` DROP COLUMN `author_id`, CHANGE `author_id_new` `author_id` CHAR(36) NOT NULL;
ALTER TABLE `refunds` DROP COLUMN `purchase_id`, CHANGE `purchase_id_new` `purchase_id` CHAR(36) NOT NULL;
ALTER TABLE `refunds` DROP COLUMN `user_id`, CHANGE `user_id_new` `user_id` CHAR(36) NOT NULL;
ALTER TABLE `sales` DROP COLUMN `author_id`, CHANGE `author_id_new` `author_id` CHAR(36) NOT NULL;
ALTER TABLE `sales` DROP COLUMN `item_id`, CHANGE `item_id_new` `item_id` CHAR(36) NOT NULL;
ALTER TABLE `sales` DROP COLUMN `user_id`, CHANGE `user_id_new` `user_id` CHAR(36) NOT NULL;
ALTER TABLE `statements` DROP COLUMN `user_id`, CHANGE `user_id_new` `user_id` CHAR(36) NOT NULL;
ALTER TABLE `sub_categories` DROP COLUMN `category_id`, CHANGE `category_id_new` `category_id` CHAR(36) NOT NULL;
ALTER TABLE `subscriptions` DROP COLUMN `plan_id`, CHANGE `plan_id_new` `plan_id` CHAR(36) NOT NULL;
ALTER TABLE `subscriptions` DROP COLUMN `user_id`, CHANGE `user_id_new` `user_id` CHAR(36) NOT NULL;
ALTER TABLE `support_earnings` DROP COLUMN `author_id`, CHANGE `author_id_new` `author_id` CHAR(36) NOT NULL;
ALTER TABLE `support_earnings` DROP COLUMN `purchase_id`, CHANGE `purchase_id_new` `purchase_id` CHAR(36) NOT NULL;
ALTER TABLE `ticket_replies` DROP COLUMN `admin_id`, CHANGE `admin_id_new` `admin_id` CHAR(36) NULL;
ALTER TABLE `ticket_replies` DROP COLUMN `ticket_id`, CHANGE `ticket_id_new` `ticket_id` CHAR(36) NOT NULL;
ALTER TABLE `ticket_replies` DROP COLUMN `user_id`, CHANGE `user_id_new` `user_id` CHAR(36) NULL;
ALTER TABLE `ticket_reply_attachments` DROP COLUMN `ticket_reply_id`, CHANGE `ticket_reply_id_new` `ticket_reply_id` CHAR(36) NOT NULL;
ALTER TABLE `tickets` DROP COLUMN `ticket_category_id`, CHANGE `ticket_category_id_new` `ticket_category_id` CHAR(36) NOT NULL;
ALTER TABLE `tickets` DROP COLUMN `user_id`, CHANGE `user_id_new` `user_id` CHAR(36) NOT NULL;
ALTER TABLE `top_nav_links` DROP COLUMN `parent_id`, CHANGE `parent_id_new` `parent_id` CHAR(36) NULL;
ALTER TABLE `transaction_items` DROP COLUMN `item_id`, CHANGE `item_id_new` `item_id` CHAR(36) NULL;
ALTER TABLE `transaction_items` DROP COLUMN `transaction_id`, CHANGE `transaction_id_new` `transaction_id` CHAR(36) NOT NULL;
ALTER TABLE `transactions` DROP COLUMN `payment_gateway_id`, CHANGE `payment_gateway_id_new` `payment_gateway_id` CHAR(36) NULL;
ALTER TABLE `transactions` DROP COLUMN `plan_id`, CHANGE `plan_id_new` `plan_id` CHAR(36) NULL;
ALTER TABLE `transactions` DROP COLUMN `purchase_id`, CHANGE `purchase_id_new` `purchase_id` CHAR(36) NULL;
ALTER TABLE `transactions` DROP COLUMN `user_id`, CHANGE `user_id_new` `user_id` CHAR(36) NOT NULL;
ALTER TABLE `uploaded_files` DROP COLUMN `category_id`, CHANGE `category_id_new` `category_id` CHAR(36) NOT NULL;
ALTER TABLE `uploaded_files` DROP COLUMN `author_id`, CHANGE `author_id_new` `author_id` CHAR(36) NOT NULL;
ALTER TABLE `user_badges` DROP COLUMN `badge_id`, CHANGE `badge_id_new` `badge_id` CHAR(36) NOT NULL;
ALTER TABLE `user_badges` DROP COLUMN `user_id`, CHANGE `user_id_new` `user_id` CHAR(36) NOT NULL;
ALTER TABLE `user_login_logs` DROP COLUMN `user_id`, CHANGE `user_id_new` `user_id` CHAR(36) NOT NULL;
ALTER TABLE `users` DROP COLUMN `level_id`, CHANGE `level_id_new` `level_id` CHAR(36) NULL;
ALTER TABLE `users` DROP COLUMN `withdrawal_method_id`, CHANGE `withdrawal_method_id_new` `withdrawal_method_id` CHAR(36) NULL;
ALTER TABLE `withdrawals` DROP COLUMN `author_id`, CHANGE `author_id_new` `author_id` CHAR(36) NOT NULL;

-- ── Phase E: Re-add FK constraints ─────────────────────────
ALTER TABLE `badges` ADD CONSTRAINT `badges_level_id_foreign` FOREIGN KEY (`level_id`) REFERENCES `levels`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `blog_articles` ADD CONSTRAINT `blog_articles_blog_category_id_foreign` FOREIGN KEY (`blog_category_id`) REFERENCES `blog_categories`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `blog_comments` ADD CONSTRAINT `blog_comments_blog_article_id_foreign` FOREIGN KEY (`blog_article_id`) REFERENCES `blog_articles`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `blog_comments` ADD CONSTRAINT `blog_comments_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `bottom_nav_links` ADD CONSTRAINT `bottom_nav_links_parent_id_foreign` FOREIGN KEY (`parent_id`) REFERENCES `bottom_nav_links`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `cart_items` ADD CONSTRAINT `cart_items_item_id_foreign` FOREIGN KEY (`item_id`) REFERENCES `items`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `cart_items` ADD CONSTRAINT `cart_items_support_period_id_foreign` FOREIGN KEY (`support_period_id`) REFERENCES `support_periods`(`id`) ON DELETE SET NULL ON UPDATE RESTRICT;
ALTER TABLE `cart_items` ADD CONSTRAINT `cart_items_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `category_options` ADD CONSTRAINT `category_options_category_id_foreign` FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `category_reviewer` ADD CONSTRAINT `category_reviewer_category_id_foreign` FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `category_reviewer` ADD CONSTRAINT `category_reviewer_reviewer_id_foreign` FOREIGN KEY (`reviewer_id`) REFERENCES `reviewers`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `favorites` ADD CONSTRAINT `favorites_item_id_foreign` FOREIGN KEY (`item_id`) REFERENCES `items`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `favorites` ADD CONSTRAINT `favorites_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `followers` ADD CONSTRAINT `followers_follower_id_foreign` FOREIGN KEY (`follower_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `followers` ADD CONSTRAINT `followers_following_id_foreign` FOREIGN KEY (`following_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `footer_links` ADD CONSTRAINT `footer_links_parent_id_foreign` FOREIGN KEY (`parent_id`) REFERENCES `footer_links`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `help_articles` ADD CONSTRAINT `help_articles_help_category_id_foreign` FOREIGN KEY (`help_category_id`) REFERENCES `help_categories`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `item_change_logs` ADD CONSTRAINT `item_change_logs_item_id_foreign` FOREIGN KEY (`item_id`) REFERENCES `items`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `item_comment_replies` ADD CONSTRAINT `item_comment_replies_item_comment_id_foreign` FOREIGN KEY (`item_comment_id`) REFERENCES `item_comments`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `item_comment_replies` ADD CONSTRAINT `item_comment_replies_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `item_comment_reports` ADD CONSTRAINT `item_comment_reports_item_comment_reply_id_foreign` FOREIGN KEY (`item_comment_reply_id`) REFERENCES `item_comment_replies`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `item_comment_reports` ADD CONSTRAINT `item_comment_reports_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `item_comments` ADD CONSTRAINT `item_comments_author_id_foreign` FOREIGN KEY (`author_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `item_comments` ADD CONSTRAINT `item_comments_item_id_foreign` FOREIGN KEY (`item_id`) REFERENCES `items`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `item_comments` ADD CONSTRAINT `item_comments_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `item_discounts` ADD CONSTRAINT `item_discounts_item_id_foreign` FOREIGN KEY (`item_id`) REFERENCES `items`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `item_histories` ADD CONSTRAINT `item_histories_admin_id_foreign` FOREIGN KEY (`admin_id`) REFERENCES `admins`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `item_histories` ADD CONSTRAINT `item_histories_item_id_foreign` FOREIGN KEY (`item_id`) REFERENCES `items`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `item_histories` ADD CONSTRAINT `item_histories_reviewer_id_foreign` FOREIGN KEY (`reviewer_id`) REFERENCES `reviewers`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `item_histories` ADD CONSTRAINT `item_histories_user_id_foreign` FOREIGN KEY (`author_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `item_review_replies` ADD CONSTRAINT `item_review_replies_item_review_id_foreign` FOREIGN KEY (`item_review_id`) REFERENCES `item_reviews`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `item_review_replies` ADD CONSTRAINT `item_review_replies_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `item_reviews` ADD CONSTRAINT `item_reviews_author_id_foreign` FOREIGN KEY (`author_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `item_reviews` ADD CONSTRAINT `item_reviews_item_id_foreign` FOREIGN KEY (`item_id`) REFERENCES `items`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `item_reviews` ADD CONSTRAINT `item_reviews_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `item_updates` ADD CONSTRAINT `item_updates_category_id_foreign` FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `item_updates` ADD CONSTRAINT `item_updates_item_id_foreign` FOREIGN KEY (`item_id`) REFERENCES `items`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `item_updates` ADD CONSTRAINT `item_updates_sub_category_id_foreign` FOREIGN KEY (`sub_category_id`) REFERENCES `sub_categories`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `item_updates` ADD CONSTRAINT `item_updates_user_id_foreign` FOREIGN KEY (`author_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `item_views` ADD CONSTRAINT `item_views_item_id_foreign` FOREIGN KEY (`item_id`) REFERENCES `items`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `items` ADD CONSTRAINT `items_category_id_foreign` FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `items` ADD CONSTRAINT `items_sub_category_id_foreign` FOREIGN KEY (`sub_category_id`) REFERENCES `sub_categories`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `items` ADD CONSTRAINT `items_user_id_foreign` FOREIGN KEY (`author_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `kyc_verifications` ADD CONSTRAINT `kyc_verifications_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `playlist_items` ADD CONSTRAINT `playlist_items_item_id_fkey` FOREIGN KEY (`item_id`) REFERENCES `items`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `playlist_items` ADD CONSTRAINT `playlist_items_playlist_id_fkey` FOREIGN KEY (`playlist_id`) REFERENCES `playlists`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `playlists` ADD CONSTRAINT `playlists_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `premium_earnings` ADD CONSTRAINT `premium_earnings_author_id_foreign` FOREIGN KEY (`author_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `premium_earnings` ADD CONSTRAINT `premium_earnings_item_id_foreign` FOREIGN KEY (`item_id`) REFERENCES `items`(`id`) ON DELETE SET NULL ON UPDATE RESTRICT;
ALTER TABLE `premium_earnings` ADD CONSTRAINT `premium_earnings_subscription_id_foreign` FOREIGN KEY (`subscription_id`) REFERENCES `subscriptions`(`id`) ON DELETE SET NULL ON UPDATE RESTRICT;
ALTER TABLE `purchases` ADD CONSTRAINT `purchases_author_id_foreign` FOREIGN KEY (`author_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `purchases` ADD CONSTRAINT `purchases_item_id_foreign` FOREIGN KEY (`item_id`) REFERENCES `items`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `purchases` ADD CONSTRAINT `purchases_sale_id_foreign` FOREIGN KEY (`sale_id`) REFERENCES `sales`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `purchases` ADD CONSTRAINT `purchases_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `referral_earnings` ADD CONSTRAINT `referral_earnings_author_id_foreign` FOREIGN KEY (`author_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `referral_earnings` ADD CONSTRAINT `referral_earnings_referral_id_foreign` FOREIGN KEY (`referral_id`) REFERENCES `referrals`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `referral_earnings` ADD CONSTRAINT `referral_earnings_sale_id_foreign` FOREIGN KEY (`sale_id`) REFERENCES `sales`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `referrals` ADD CONSTRAINT `referrals_author_id_foreign` FOREIGN KEY (`author_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `referrals` ADD CONSTRAINT `referrals_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `refresh_tokens` ADD CONSTRAINT `refresh_tokens_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `refund_replies` ADD CONSTRAINT `refund_replies_refund_id_foreign` FOREIGN KEY (`refund_id`) REFERENCES `refunds`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `refund_replies` ADD CONSTRAINT `refund_replies_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `refunds` ADD CONSTRAINT `refunds_author_id_foreign` FOREIGN KEY (`author_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `refunds` ADD CONSTRAINT `refunds_purchase_id_foreign` FOREIGN KEY (`purchase_id`) REFERENCES `purchases`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `refunds` ADD CONSTRAINT `refunds_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `sales` ADD CONSTRAINT `sales_author_id_foreign` FOREIGN KEY (`author_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `sales` ADD CONSTRAINT `sales_item_id_foreign` FOREIGN KEY (`item_id`) REFERENCES `items`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `sales` ADD CONSTRAINT `sales_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `statements` ADD CONSTRAINT `statements_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `sub_categories` ADD CONSTRAINT `sub_categories_category_id_foreign` FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `subscriptions` ADD CONSTRAINT `subscriptions_plan_id_foreign` FOREIGN KEY (`plan_id`) REFERENCES `plans`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `subscriptions` ADD CONSTRAINT `subscriptions_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `support_earnings` ADD CONSTRAINT `support_earnings_author_id_foreign` FOREIGN KEY (`author_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `support_earnings` ADD CONSTRAINT `support_earnings_purchase_id_foreign` FOREIGN KEY (`purchase_id`) REFERENCES `purchases`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `ticket_replies` ADD CONSTRAINT `ticket_replies_admin_id_foreign` FOREIGN KEY (`admin_id`) REFERENCES `admins`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `ticket_replies` ADD CONSTRAINT `ticket_replies_ticket_id_foreign` FOREIGN KEY (`ticket_id`) REFERENCES `tickets`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `ticket_replies` ADD CONSTRAINT `ticket_replies_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `ticket_reply_attachments` ADD CONSTRAINT `ticket_reply_attachments_ticket_reply_id_foreign` FOREIGN KEY (`ticket_reply_id`) REFERENCES `ticket_replies`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `tickets` ADD CONSTRAINT `tickets_ticket_category_id_foreign` FOREIGN KEY (`ticket_category_id`) REFERENCES `ticket_categories`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `tickets` ADD CONSTRAINT `tickets_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `top_nav_links` ADD CONSTRAINT `top_nav_links_parent_id_foreign` FOREIGN KEY (`parent_id`) REFERENCES `top_nav_links`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `transaction_items` ADD CONSTRAINT `transaction_items_item_id_foreign` FOREIGN KEY (`item_id`) REFERENCES `items`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `transaction_items` ADD CONSTRAINT `transaction_items_transaction_id_foreign` FOREIGN KEY (`transaction_id`) REFERENCES `transactions`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `transactions` ADD CONSTRAINT `transactions_payment_gateway_id_foreign` FOREIGN KEY (`payment_gateway_id`) REFERENCES `payment_gateways`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `transactions` ADD CONSTRAINT `transactions_plan_id_foreign` FOREIGN KEY (`plan_id`) REFERENCES `plans`(`id`) ON DELETE SET NULL ON UPDATE RESTRICT;
ALTER TABLE `transactions` ADD CONSTRAINT `transactions_purchase_id_foreign` FOREIGN KEY (`purchase_id`) REFERENCES `purchases`(`id`) ON DELETE SET NULL ON UPDATE RESTRICT;
ALTER TABLE `transactions` ADD CONSTRAINT `transactions_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `uploaded_files` ADD CONSTRAINT `uploaded_files_category_id_foreign` FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `uploaded_files` ADD CONSTRAINT `uploaded_files_user_id_foreign` FOREIGN KEY (`author_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `user_badges` ADD CONSTRAINT `user_badges_badge_id_foreign` FOREIGN KEY (`badge_id`) REFERENCES `badges`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `user_badges` ADD CONSTRAINT `user_badges_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `user_login_logs` ADD CONSTRAINT `user_login_logs_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `users` ADD CONSTRAINT `users_level_id_foreign` FOREIGN KEY (`level_id`) REFERENCES `levels`(`id`) ON DELETE SET NULL ON UPDATE RESTRICT;
ALTER TABLE `users` ADD CONSTRAINT `users_withdrawal_method_id_foreign` FOREIGN KEY (`withdrawal_method_id`) REFERENCES `withdrawal_methods`(`id`) ON DELETE SET NULL ON UPDATE RESTRICT;
ALTER TABLE `withdrawals` ADD CONSTRAINT `withdrawals_user_id_foreign` FOREIGN KEY (`author_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;

SET FOREIGN_KEY_CHECKS = 1;

-- Migration complete: 81 tables, 95 FKs